server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/state_machine?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 18000000
      connection-timeout: 30000
      pool-name: HikariCP

mybatis:
  type-aliases-package: com.spencer.statemachine.pojo
  mapper-locations: classpath:/com/spencer/statemachine/dao/mapping/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl