package com.spencer.statemachine.dao;

import com.spencer.statemachine.entity.OrderTest;

import java.util.List;

/**
 * @author lichao
 * @date 2018/11/27 3:21 PM
 **/
public interface OrderTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    int insert(OrderTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    int insertSelective(OrderTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    OrderTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTest record);

    List<OrderTest> listOrder();
}